[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2

[[main]]
    identifier = "about"
    name = "About me"
    url = "/about"
    weight = 3

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 4

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 5

[[main]]
    identifier = "donate"
    name = "Donate"
    url = "https://ko-fi.com/nixentric"
    weight = 6
    
# Social Media Configuration

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "#"
    weight = 1

[[social]]
    identifier = "instagram"
    name = "Instagram"
    url = "#"
    weight = 2

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "#"
    weight = 3
